
name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Getting Files
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'corretto'
          cache: maven
      - name: Preparing new version info
        id: version
        uses: PaulHatch/semantic-version@v4.0.2
        with:
          tag_prefix: "v"
          major_pattern: "maj"
          minor_pattern: "min"
          format: "${major}.${minor}.${patch}"
          namespace: develop
          change_path: "."
          short_tags: false
          bump_each_commit: false

      - name: Build
        run: mvn -B package -Dversion=${{steps.version.outputs.version_tag}} --file pom.xml

      - name: Unit Tests
        run: mvn -B test -Dversion=${{steps.version.outputs.version_tag}} --file pom.xml